---
title: "Titanic sinking"
author: "Stefano Galeano"
date: "19 dicembre 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
train <- read.csv('train.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c(""))
train$Survived <- as.factor(train$Survived)
train$Sex <- as.factor(train$Sex)
train$Embarked <- as.factor(train$Embarked)

test <- read.csv('test.csv', header = TRUE,stringsAsFactors = FALSE, na.strings = c(""))
test$Sex <- as.factor(test$Sex)
test$Embarked <- as.factor(test$Embarked)
```
```{r}
train$Ticket.initials <- gsub(pattern = "^((.*) )?(\\d*)?$", x=train$Ticket, replacement="\\2")
train$Ticket.initials <- as.factor(train$Ticket.initial)
train$Ticket.number <- gsub(pattern = "^((.*) )?(\\d*)?$", x=train$Ticket, replacement="\\3")
train$Ticket.number <- gsub(pattern = "^LINE$", x=train$Ticket.number, replacement="0")
train$Ticket.number <- as.integer(train$Ticket.number)

test$Ticket.initials <- gsub(pattern = "^((.*) )?(\\d*)?$", x=test$Ticket, replacement="\\2")
test$Ticket.initials <- as.factor(test$Ticket.initial)
test$Ticket.number <- gsub(pattern = "^((.*) )?(\\d*)?$", x=test$Ticket, replacement="\\3")
test$Ticket.number <- gsub(pattern = "^LINE$", x=test$Ticket.number, replacement="0")
test$Ticket.number <- as.integer(test$Ticket.number)
```
```{r}
train$Name.surname <- gsub(pattern = "([\\w|\\-| |']*), ([\\w| ]*\\.) (.*)", x=train$Name, replacement="\\1", ignore.case=TRUE, perl = TRUE)
train$Name.title <- gsub(pattern = "([\\w|\\-| |']*), ([\\w| ]*\\.) (.*)", x=train$Name, replacement="\\2", ignore.case=TRUE, perl = TRUE)
train$Name.title <- as.factor(train$Name.title)

test$Name.surname <- gsub(pattern = "([\\w|\\-| |']*), ([\\w| ]*\\.) (.*)", x=test$Name, replacement="\\1", ignore.case=TRUE, perl = TRUE)
test$Name.title <- gsub(pattern = "([\\w|\\-| |']*), ([\\w| ]*\\.) (.*)", x=test$Name, replacement="\\2", ignore.case=TRUE, perl = TRUE)
test$Name.title <- as.factor(test$Name.title)

# used in order to avoid error when predicting in the test dataset
levels(train$Name.title) <- union(levels(train$Name.title),levels(test$Name.title))
```
```{r}
train$Cabin[is.na(train$Cabin)] <- "U" # Unknown
train$Cabin.deck <- gsub(pattern = "^(\\D)(\\d{0,3}).*$", x=train$Cabin, replacement="\\1", ignore.case=TRUE, perl = TRUE)
train$Cabin.deck <- as.factor(train$Cabin.deck)
train$Cabin.room <- gsub(pattern = "^(\\D)(\\d{0,3}).*$", x=train$Cabin, replacement="\\2", ignore.case=TRUE, perl = TRUE)

test$Cabin[is.na(test$Cabin)] <- "U" # Unknown
test$Cabin.deck <- gsub(pattern = "^(\\D)(\\d{0,3}).*$", x=test$Cabin, replacement="\\1", ignore.case=TRUE, perl = TRUE)
test$Cabin.deck <- as.factor(test$Cabin.deck)
test$Cabin.room <- gsub(pattern = "^(\\D)(\\d{0,3}).*$", x=test$Cabin, replacement="\\2", ignore.case=TRUE, perl = TRUE)
```
```{r}
train$Name <- NULL
train$Name.surname <- NULL
train$Cabin <- NULL
train$Cabin.room <- NULL
train$Ticket <- NULL
train$Fare <- NULL
train$Ticket.number <- NULL
train$Ticket.initials <- NULL
train$PassengerId <- NULL

test$Name <- NULL
test$Name.surname <- NULL
test$Cabin <- NULL
test$Cabin. <- NULL
test$Ticket <- NULL
test$Fare <- NULL
test$Ticket.number <- NULL
test$Ticket.initials <- NULL
```
library(caret)

set.seed(4974)
inTrain <- createDataPartition(train$Survived,p=.75,list = FALSE)

train.train <- train[inTrain,]
train.test <- train[-inTrain,]
df <- train.train
```
library(Amelia)
missmap(df, col=c('grey', 'steelblue'), y.cex=0.5, x.cex=0.8)
```
```{r}
library(mice)
set.seed(5102)
imp.df <- mice(df, method='rf', printFlag=FALSE)
df <- complete(imp.df)
# missmap(df, col=c('grey', 'steelblue'), y.cex=0.5, x.cex=0.8)
```
```{r}
set.seed(72034)

ctrl <- trainControl(method = "cv")
model <- train(Survived~.,data = df,method="bayesglm", trControl = ctrl)
predicted <- predict(model)

model
confusionMatrix(predicted,df$Survived)
```
